webprofe/main/routes.py
from flask import current_app, render_template, request, Blueprint, url_for, redirect, flash, session, Response, send_file, abort, jsonify
from webprofe import db, excel
from webprofe.models import Profe, Bajas, Dependencia, Solicitud, ARG, Telefono, xstr, User, Anotacion
from webprofe.main.forms import ElegirLocalidad, SolicitarLentes
from fpdf import FPDF
from flask_login import login_required, current_user
from functools import wraps
from datetime import datetime, timezone
from io import BytesIO
import zipfile
import os
from pathlib import Path
import re
import qrcode
import zlib
from base64 import urlsafe_b64encode as b64e, urlsafe_b64decode as b64d
from werkzeug.utils import secure_filename
import secrets
from werkzeug.wsgi import FileWrapper
import subprocess
from sys import platform
from sqlalchemy.sql import text
from webprofe.users.signer import sign_pdf
from webprofe.users.utils import solo_admins
from webprofe import extract


main = Blueprint('main', __name__)
chars = 3  # minimo de caracteres a buscar 


def actualizando(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if os.path.exists(os.path.join(current_app.root_path, 'lock_db')):
            return render_template('inicio_progreso.html')
        else:
            return f(*args, **kwargs)
    return decorated_function


def buscar(query, param=None):
    # connect to db
    try:
        engine = db.engine
        connection = engine.connect()
    except:
        print("Error")
        return
    # run a query and get the results
    s = text(query)
    results = connection.execute(s, {"x": param}).fetchall()
    result = results
    connection.close()
    return result


def upload_scan(archivo, nombre):
    sfilename = secure_filename(archivo.filename)
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(sfilename)
    filename = nombre + '_' + random_hex + f_ext
    archivo.save(os.path.join(current_app.root_path, 'static/uploads', filename))
    return filename


def agregar_telefono_paciente(paciente, num_tel):
    num_tel = re.sub("[^+0-9]", "", num_tel)
    buscar_tel = Telefono.query \
        .filter(Telefono.Numero_tel == num_tel) \
            .filter(Telefono.PROFE_Numero_Doc == paciente.Numero_Doc) \
                .first()
    if buscar_tel:
        return False
    tel = Telefono(PROFE_Numero_Doc=paciente.Numero_Doc,
                Numero_tel=num_tel)
    db.session.add(tel)
    db.session.commit()
    return True


@main.route("/solicitud_anteojos", methods=['GET', 'POST'])
@actualizando
@solo_admins
@login_required
def crear_solicitud_anteojos():
    form = SolicitarLentes()
    form.dependencia.choices.extend([(x.id, x.nombre) for x in Dependencia.query.order_by(Dependencia.nombre.asc()).all()])
    if form.validate_on_submit():
        buscar = Solicitud.query.filter(Solicitud.numero_ps == form.numero_ps.data.strip()).first()
        if buscar:
            flash("<span class='fs-5'>Ya hay un pedido cargado con ese numero de PS. Ref.: {str(buscar.id)}</span>", "danger")
            return redirect(request.url)
        solicitud = Solicitud(numero_ps=form.numero_ps.data.strip(),
                            numero_doc=form.numero_doc.data.strip(),
                            dependencia_id=form.dependencia.data)
        paciente = Profe.query.filter(Profe.Numero_Doc == form.numero_doc.data).first()
        if request.form['telefono_real_1']:
            if not agregar_telefono_paciente(paciente, request.form['telefono_real_1']):
                flash(f'<span class="fs-5">El número ya está cargado</span>', "warning")
        if request.form['telefono_real_2']:
            if not agregar_telefono_paciente(paciente, request.form['telefono_real_2']):
                flash(f'<span class="fs-5">El número ya está cargado</span>', "warning")
        nombre_paciente = re.sub(r'[\\/*?:"<>|]', "", paciente.ApeNom)
        nombre_paciente = nombre_paciente.strip().replace(" ", "_")
        receta = upload_scan(form.receta.data, f"{str(paciente.Numero_Doc)}_{nombre_paciente}")
        solicitud.receta = receta
        solicitud.nombre_paciente = paciente.ApeNom.strip()
        db.session.add(solicitud)
        db.session.commit()
        flash(f"<span class='fs-5'>Se registró la solicitud con éxito. Número de referencia: {str(solicitud.id)}</span>", "success")
        return redirect(url_for('main.crear_solicitud_anteojos'))
    return render_template('crear_solicitud.html', form=form, title="Solicitar lentes")


@main.route("/extracto_zip", methods=['POST'])
@actualizando
@solo_admins
@login_required
def zipped_data():
    if request.method == 'POST':
        THIS_FOLDER = os.path.dirname(os.path.abspath(__file__))
        rootpath = Path(THIS_FOLDER)
        dir_uploads = os.path.join(rootpath.parent.absolute(), 'static', 'uploads')
        fileName = f"recetas_{datetime.utcnow().strftime('%d-%m-%Y')}.zip"
        memory_file = BytesIO()
        lista_ids = [int(x) for x in request.form.getlist('chk-extracto')]
        with zipfile.ZipFile(memory_file, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for i in lista_ids:
                sol = Solicitud.query.get_or_404(i)
                ruta_receta = os.path.join(dir_uploads, sol.receta)
                zipf.write(ruta_receta, os.path.basename(ruta_receta))
        memory_file.seek(0)
        w = FileWrapper(memory_file)
        resp = Response(w, mimetype="application/zip", direct_passthrough=True)
        resp.headers['Content-Disposition'] = f'attachment; filename="{fileName}"'
        return resp
        # return send_file(memory_file,
        #                 attachment_filename=fileName,
        #                 as_attachment=True)


@main.route("/extracto_solic", methods=['POST'])
@actualizando
@solo_admins
@login_required
def extracto_solic():
    if request.method == 'POST':
        lista_ids = [int(x) for x in request.form.getlist('chk-extracto')]
        ret = [['N° PS', 'Fecha', 'DNI', 'Nombre', 'Edad', 'Tipo pensión', 'Tel.', 'Efector']]
        for i in lista_ids:
            sol = Solicitud.query.get_or_404(i)
            ret.append([sol.numero_ps,
                        sol.fecha_printable(),
                        sol.numero_doc,
                        sol.nombre_paciente,
                        sol.edad(),
                        sol.ley_aplicada(),
                        sol.telefonos_paciente(),
                        sol.dependencia.nombre])
        return excel.make_response_from_array(ret, "xlsx", file_name=f"extracto_{datetime.utcnow().strftime('%d-%m-%Y')}")


@main.route("/gestionar", methods=['POST'])
@actualizando
@solo_admins
@login_required
def gestionar():
    if request.method == 'POST':
        lista_ids = [int(x) for x in request.form.getlist('chk-extracto')]
        for i in lista_ids:
            sol = Solicitud.query.get_or_404(i)
            sol.gestionada = True
        db.session.commit()
        return redirect(url_for('main.ver_solicitudes'))
    

@main.route("/ver_solicitud", methods=['POST'])
@actualizando
@login_required
def ver_solicitud_anteojos():
    if request.method == 'POST':
        sol_id = request.form['solicitud_id']
        sol = Solicitud.query.get_or_404(sol_id)
        return render_template('solicitud_anteojos.html', sol=sol, title=f"Solicitud lentes N° {sol.id}")

    
@main.route("/eliminar_gestionadas", methods=['POST'])
@actualizando
@solo_admins
@login_required
def eliminar_gestionadas():
    if request.method == 'POST':
        THIS_FOLDER = os.path.dirname(os.path.abspath(__file__))
        rootpath = Path(THIS_FOLDER)
        dir_uploads = os.path.join(rootpath.parent.absolute(), 'static', 'uploads')
        solicitudes = Solicitud.query \
            .filter(Solicitud.gestionada.is_(True)) \
                .filter(Solicitud.receta.isnot(None)) \
                    .all()
        cant = len(solicitudes)
        counter = 0
        if solicitudes:
            for i in solicitudes:
                ruta_receta = os.path.join(dir_uploads, i.receta)
                try:
                    os.remove(ruta_receta)
                    counter += 1
                except OSError:
                    pass
                i.receta = None
            db.session.commit()
            flash(f"<span class='fs-5'>Se borraron {counter} de {cant} archivos</span>", "warning")
        else:
            flash(f"<span class='fs-5'>No hay archivos para borrar</span>", "warning")
        return redirect(url_for('main.ver_solicitudes'))


@main.route("/listado_solicitudes", methods=['GET'])
@actualizando
@solo_admins
@login_required
def ver_solicitudes():
    porcentaje = None
    if platform == "linux":
        disponible = 512.0
        if os.environ.get('PYTHONANYWHERE_DOMAIN'):
            output = subprocess.getoutput('du -cs /tmp ~ | awk "/total/ {print $1}"')
            usado = int(output.split()[0]) / 1024
        else:
            output = subprocess.getoutput("du -cs /home/guillermo/Descargas | awk '{print $1}'")
            usado = int(output.split()[0]) / 1024
        porcentaje = round((usado / disponible) * 100)
    else:
        porcentaje = 50
    solicitudes = Solicitud.query.order_by(Solicitud.fecha.asc()).all()
    solicitudes_pendientes = Solicitud.query.filter(Solicitud.gestionada.is_(False)).count()
    return render_template('listado_anteojos.html', solicitudes=solicitudes, 
                           title="Solicitudes de anteojos", porcentaje=porcentaje,
                           solicitudes_pendientes=solicitudes_pendientes)


@main.route("/purgar_solicitudes", methods=['GET'])
@actualizando
@solo_admins
@login_required
def purgar_solicitudes():
    solicitudes = Solicitud.query.all()
    for s in solicitudes:
        pac = Profe.query.filter(s.numero_doc == Profe.Numero_Doc).first()
        if not pac:
            print(f'Eliminando {s}')
            db.session.delete(s)
    db.session.commit()

webprofe/users/routes.py
from flask import render_template, request, Blueprint, url_for, redirect, flash, abort
from flask_login import current_user, login_required, login_user, logout_user
from webprofe import db, bcrypt
from webprofe.models import Dependencia, User
from webprofe.users.forms import RegistrationForm, LoginForm, RequestResetForm, ResetPasswordForm
from webprofe.users.utils import is_safe_url, solo_admins, send_reset_email, generar_certs_user


users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.inicio'))
    form = RegistrationForm()
    form.dependencia.choices.extend([(x.id, x.nombre) for x in Dependencia.query.order_by(Dependencia.nombre.asc()).all()])
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(dependencia_id=form.dependencia.data, 
                    email=form.email.data.strip(), 
                    nombre=form.nombre.data.strip().title(), 
                    apellido=form.apellido.data.strip().title(), 
                    dni=int(form.dni.data.strip()),
                    password=hashed_password, 
                    rol_id=2)
        db.session.add(user)
        db.session.commit()
        flash("<span class='fs-5'>El usuario ha sido creado con éxito</span>", 'success')
        if not generar_certs_user(user):
            flash("<span class='fs-5'>Error al generar claves de usuario</span>", 'danger')
        return redirect(url_for('main.inicio'))
    return render_template('register.html', title='Registrar nuevo usuario', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        if current_user.baja:
            flash("<span class='fs-5'>Su usario ha sido dado de baja</span>", 'danger')
            return redirect(url_for('users.logout'))
        else:
            return redirect(url_for('main.inicio'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(dni=form.dni.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            if user.baja:
                flash("<span class='fs-5'>Su usario ha sido dado de baja</span>", 'danger')
                return redirect(request.url)
            else:
                login_user(user, remember=form.remember.data)
                db.session.commit()
                next_page = request.args.get('next')
                if not is_safe_url(next_page):
                    abort(400)
                return redirect(next_page or url_for('main.inicio'))
        else:
            flash("<span class='fs-5'>Inicio de sesión fallido. Verifique e-mail y contraseña</span>", 'danger')
    return render_template('login.html', title='Iniciar sesión', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.inicio'))


@users.route("/user/<int:user_id>/eliminar", methods=['GET'])
@login_required
@solo_admins
def eliminar_usuario(user_id):
    user = User.query.get_or_404(user_id)
    if user.baja:
        user.baja = False
        db.session.commit()
        flash(f'<span class="fs-5">Se activó al usuario {user.nombre} {user.apellido}</span>', 'success')
    else:
        user.baja = True
        db.session.commit()
        flash(f'<span class="fs-5">Se dio de baja al usuario {user.nombre} {user.apellido}</span>', 'success')
    return redirect(url_for('users.ver_usuarios'))


@users.route("/user/<int:user_id>/modificar", methods=['GET'])
@login_required
@solo_admins
def modificar_usuario(user_id):
    user = User.query.get_or_404(user_id)
    if user.rol_id == 1:
        user.rol_id = 2
    else:
        user.rol_id = 1
    flash(f'<span class="fs-5">Se modificó el usuario {user.nombre} {user.apellido}</span>', 'success')
    db.session.commit()
    return redirect(url_for('users.ver_usuarios'))


@users.route("/user/<int:user_id>/renovar_certs", methods=['GET'])
@login_required
@solo_admins
def renovar_certs(user_id):
    user = User.query.get_or_404(user_id)
    generar_certs_user(user)
    flash(f'<span class="fs-5">Se renovaron los certificados de {user.nombre} {user.apellido}</span>', 'success')
    return redirect(url_for('users.ver_usuarios'))


@users.route("/users", methods=['GET', 'POST'])
@login_required
@solo_admins
def ver_usuarios():
    users = User.query.all()
    # users = User.query.filter_by(User.rol_id > 1).all()
    return render_template('users.html', title='Ver usuarios', users=users)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.inicio'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if not user:
            flash('<span class="fs-5">No existen usuarios registrados con ese correo electrónico.</span>', 'info')
            return redirect(url_for('users.login'))
        send_reset_email(user)
        flash(f'<span class="fs-5">Se ha enviado un email a {user.email} con instrucciones para restablecer la contraseña. Revisar carpeta de correo no deseado.</span>', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Restablecer contraseña', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.inicio'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('<span class="fs-5">Token inválido o expirado.</span>', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('<span class="fs-5">Su contraseña ha sido actualizada. Ya puede iniciar sesión.</span>', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Retablecer contraseña', form=form)


# @users.route("/hacer_title_case", methods=['GET', 'POST'])
# def hacer_title_case():
#     users = User.query.all()
#     for u in users:
#         u.nombre = u.nombre.title()
#         u.apellido = u.apellido.title()
#     db.session.commit()
#     return redirect(url_for('main.inicio'))

webprofe/templates/inicio_progreso.html
{% extends "layout.html" %}
{% block content %}
  <style>
    #centro {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
    }
  </style>
  <div id="centro" class="text-center">
    <img src="{{ url_for('static', filename='Under_construction_animated.gif') }}" alt="Trabajando en eso..." />
    <p class="text-center fs-4">
      La base de datos se está actualizando. Intente nuevamente en unos minutos.
    </p>    
  </div>
{% endblock content %}

webprofe/templates/listado_anteojos.html
{% extends "layout.html" %}
{% block content %}
  {% if solicitudes %}
    <div class="row">
      <div class="col-4">
        {{ solicitudes_pendientes }} pedido(s) pendiente(s) de gestión
      </div>
      <div class="col-8">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" id="mostrar_gestionadas" name="mostrar_gestionadas">
          <label class="form-check-label" for="mostrar_gestionadas">Mostrar gestionadas</label>
        </div>
      </div>
    </div>
    <form id="form" action="" method="POST">
      <table id="table_id" class="table-sort table-arrows remember-sort table table-no-outer-padding table-hover">
        <thead>
          <tr>
            <th class="text-nowrap">N° PS</th>
            <th class="text-nowrap">N° Doc</th>
            <th class="text-nowrap">Nombre</th>
            <th class="text-nowrap">Edad</th>
            <th class="text-nowrap">Tipo pensión</th>
            <th class="text-nowrap disable-sort">Teléfonos</th>
            <th class="text-nowrap dates-dmy-sort">Fecha</th>
            <th lass="text-nowrap">Efector</th>
            <th lass="text-nowrap">N° Ref</th>
            <th class="text-nowrap disable-sort">Receta</th>
            <th class="text-nowrap disable-sort">
              <input class="form-check-input" type="checkbox" id="select-all">
            </th>
          </tr>
        </thead>
        <tbody id="myTable">
          {% for i in solicitudes %}
            {% if i.gestionada %}
              <tr class="table-danger gest mt-2">
            {% else %}
              <tr class="mt-2">
            {% endif %}
              <td>{{ i.numero_ps }}</td>
              <td>{{ i.numero_doc }}</td>
              <td>{{ i.nombre_paciente }}</td>
              <td>{{ i.edad() }}</td>
              <td>{{ i.ley_aplicada() }}</td>
              <td>
                {% if i.telefonos_paciente() %}
                  {{ i.telefonos_paciente() }}
                {% endif %}
              </td>
              <td>{{ i.fecha_printable() }}</td>
              <td>{{ i.dependencia.nombre }}</td>
              <td>{{ i.id }}</td>
              {% if i.receta %}
                <td><a target="_blank" class="btn btn-sm" href="{{ url_for('static', filename='uploads/' + i.receta) }}"><i class="fas fa-file-prescription"></i></a></td>
              {% else %}
                <td>-</td>
              {% endif %}
              <td>
                <input class="form-check-input" type="checkbox" id="checkbox-{{ i.id }}" name="chk-extracto" value="{{ i.id }}" aria-label="Checkbox with no label">
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <div class="d-flex justify-content-center align-items-center">
        <button id="btn-zip" class="mx-2 btn btn-primary">Bajar Zip con recetas</button>
        <button id="btn-xls" class="mx-2 btn btn-primary">Bajar Excel con detalle</button>
        <button id="btn-gest" class="mx-2 btn btn-primary">Marcar como gestionadas</button>
      </div>
    </form>
    {% if porcentaje %}
      <div class="d-flex justify-content-center align-items-center mt-3 mb-3">
        <div style="min-width: 50vw;" class="progress" role="progressbar" aria-label="Basic example" aria-valuenow="{{porcentaje}}" aria-valuemin="0" aria-valuemax="100">
          <div class="progress-bar" style="width: {{porcentaje}}%"></div>
        </div>
        <div>
          <form onsubmit="return confirm('ATENCION: Se borrarán archivos de solicitudes ya gestionadas. ¿Continuar?');" action="{{ url_for('main.eliminar_gestionadas') }}" method="post">
            <input type="hidden" value="{{ csrf_token }}">
            <input class="ms-1 btn btn-sm btn-danger" value="Liberar espacio" type="submit"/>
          </form>        
        </div>
      </div>
    {% endif %}
  {% else %}
    <p>No hay solicitudes</p>
  {% endif %}
  <script>
    $('#btn-zip').click(function(){
      if(jQuery('#form input[type=checkbox]:checked').length) {
        $('#form').attr('action', '{{ url_for("main.zipped_data") }}');
        $('#form').submit();
      } else {
        Swal.fire({
          icon: 'warning',
          title: 'Atención',
          text: 'No hay solicitudes seleccionadas',
        });
      }
    });
    $('#btn-xls').click(function(){
      if(jQuery('#form input[type=checkbox]:checked').length) {
        $('#form').attr('action', '{{ url_for("main.extracto_solic") }}');
        $('#form').submit();
      } else {
        Swal.fire({
          icon: 'warning',
          title: 'Atención',
          text: 'No hay solicitudes seleccionadas',
        });
      }
    });
    $('#btn-gest').click(function(){
      if(jQuery('#form input[type=checkbox]:checked').length) {
        $('#form').attr('action', '{{ url_for("main.gestionar") }}');
        $('#form').submit()
      } else {
        Swal.fire({
          icon: 'warning',
          title: 'Atención',
          text: 'No hay solicitudes seleccionadas',
        });
      }
    });
    $("#mostrar_gestionadas").change(function(){
      var self = this;
      $("#table_id tr.gest").toggle(self.checked); 
    }).change();
  </script>
  <script>
    $(document).ready(function () {
      $("#select-all").change(function () {
        $("table tr:visible input:checkbox").prop('checked', $(this).prop("checked"));
      });
    });
  </script>
{% endblock content %}

webprofe/templates/login.html
{% extends "layout.html" %}
{% block content %}
  <style>
    #form_login {
      left      : 50%;
      top       : 50%;
      position  : absolute;
      transform : translate(-50%, -50%);
    }
  </style>
  <form id="form_login" onsubmit="submitBtnSpinner(this.submitted, ' Espere...')" action="#" enctype="multipart/form-data" method="post">
    {{ form.hidden_tag() }}
    <div class="my-4 text-center">
      <p class="fs-4">Iniciar sesión</p>
    </div>
    <div class="my-4 form-floating">
      {% if form.dni.errors %}
        {{ form.dni(class="form-control form-control-lg remove-nonnum is-invalid", placeholder="Número de DNI") }}
        <div class="invalid-feedback">
          {% for error in form.dni.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        </div>
      {% else %}
        {{ form.dni(class="form-control form-control-lg remove-nonnum", placeholder="Número de DNI") }}
      {% endif %}
      {{ form.dni.label(for="dni") }}
    </div>
    <div class="my-4 form-floating">
      {% if form.password.errors %}
        {{ form.password(class="form-control form-control-lg is-invalid", placeholder="Contraseña") }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        </div>
      {% else %}
        {{ form.password(class="form-control form-control-lg", placeholder="Contraseña") }}
      {% endif %}
      {{ form.password.label(for="password") }}
    </div>
    <div class="form-check d-flex justify-content-center">
      <input class="form-check-input me-2" type="checkbox" value="0" name="remember" id="remember">
      <label class="form-check-label" for="remember">
        Recordarme
      </label>
    </div>    
    <div class="my-4 text-center">
      <div class="d-flex justify-content-around align-items-center">
        <button href="{{ url_for('users.register') }}" class="btn btn-lg btn-primary" type="submit" role="button"><i class="fas fa-sign-in-alt"></i> Ingresar</button>
        <a href="{{ url_for('users.register') }}" class="btn btn-info" type="button" role="button">Registrarse</a>
      </div>
      <p class="mt-2">
        <a class="text-muted small" href="{{ url_for('users.reset_request') }}">¿Olvidó su contraseña?</a>
      </p>
    </div>
  </form>
{% endblock content %}

webprofe/templates/users.html
{% extends "layout.html" %}
{% block content %}
  {% if users %}
    <table id="table_id" class="table-sort table-arrows remember-sort table table-no-outer-padding table-hover">
      <thead>
        <tr>
          <th class="text-nowrap">ID</th>
          <th class="text-nowrap">Dep.</th>
          <th class="text-nowrap">Nombre</th>
          <th class="text-nowrap">DNI</th>
          <th lass="text-nowrap">Email</th>
          <th lass="text-nowrap disable-sort">Rol</th>
          <th class="text-nowrap dates-dmy-sort">Fecha</th>
          <th class="text-nowrap dates-dmy-sort">Venc.</th>
          <th class="text-nowrap disable-sort">
          </th>
        </tr>
      </thead>
      <tbody id="myTable">
        {% for i in users %}
          {% if i.baja %}
            <tr class="table-danger">
          {% else %}
            <tr class="">
          {% endif %}
            <td>{{ i.id }}</td>
            <td>{{ i.dependencia.nombre }}</td>
            <td>{{ i.nombre }} {{ i.apellido }}</td>
            <td>{{ i.dni }}</td>
            <td>{{ i.email }}</td>
            <td>{{ i.rol.descripcion }}</td>
            <td>{{ i.fecha_printable() }}</td>
            <td>{{ i.fecha_venc_cert() }}</td>
            <td>
              <div class="d-flex align-items-center flex-nowrap">
                {% if i.baja %}
                  <a data-bs-toggle="tooltip" data-bs-title="Habilitar" data-bs-placement="top" href="{{ url_for('users.eliminar_usuario', user_id=i.id) }}" class="btn btn-sm btn-info"><i class="fas fa-angle-up"></i></a>
                {% else %}
                  {% if i.rol_id == 2 %}
                    <a data-bs-toggle="tooltip" data-bs-title="Hacer admin" data-bs-placement="top" href="{{ url_for('users.modificar_usuario', user_id=i.id) }}" class="btn btn-sm btn-primary"><i class="fas fa-user-shield"></i></a>
                  {% else %}
                    <a data-bs-toggle="tooltip" data-bs-title="Quitar admin" data-bs-placement="top" href="{{ url_for('users.modificar_usuario', user_id=i.id) }}" class="btn btn-sm btn-warning"><i class="fas fa-user-minus"></i></a>
                  {% endif %}
                  <a data-bs-toggle="tooltip" data-bs-title="Eliminar" data-bs-placement="top" href="{{ url_for('users.eliminar_usuario', user_id=i.id) }}" class="ms-1 btn btn-sm btn-danger"><i class="fas fa-trash-alt"></i></a>
                  <a data-bs-toggle="tooltip" data-bs-title="Renovar certificado" data-bs-placement="top" href="{{ url_for('users.renovar_certs', user_id=i.id) }}" class="ms-1 btn btn-sm btn-secondary"><i class="fas fa-sync"></i></a>
                {% endif %}
              </div>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No hay usuarios</p>
  {% endif %}
{% endblock content %}